name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  exif: ^3.3.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1
  flutter_local_notifications: ^19.5.0
  flutter_login: ^6.0.0
  flutter_map: ^8.2.2
  flutter_secure_storage: ^10.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  google_mlkit_text_recognition: ^0.15.0
  http: ^1.5.0
  image: ^4.5.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  map_themes: ^1.0.0
  mnc_identifier_ocr: ^1.0.23
  shared_preferences: ^2.5.4
  socket_io_client: ^3.1.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\login_6681204.png
    - assets\logo.png
    - assets\